frame_processing:
    ros__parameters:
        mobile_frame_topic: "glasses_camera_frame"
        fixed_frame_topic: "fixed_camera_frame"
        info_frame_topic: "displaying_info"
        rps: 10
fixed_camera:
    ros__parameters:
        camera_idx: 4
        frame_topic: "fixed_camera_frame"
        fps: 10
server_endpoint:
    ros__parameters:
        ROS_IP: "192.168.1.72"
