/**:
    ros__parameters:
        mobile_frame_topic: "glasses_camera_frame"
        fixed_frame_topic: "fixed_camera_frame"
        info_frame_topic: "displaying_info"
        raw_point_topic: "target_point"
        rps: 7
fixed_camera:
    ros__parameters:
        camera_idx: 4
        frame_topic: "fixed_camera_frame"
        fps: 10
camera_calibration:
    ros__parameters:
        image_topic: "fixed_camera_frame"
        save_conf_prefix: "src/cobot-ar-pkg/config/"
        save_conf_postfix: "_static"
        images_dir: "images/test"
        is_compressed: False
point_processing:
    ros__parameters:
        go_to_point_service: "go_to_point"
        max_error_meters: 0.01
        window_time_sec: 1.5
